services:
  db:
    image: mysql:8.0
    container_name: korus-mysql
    restart: unless-stopped
    env_file:
      - ./.env.prod
    volumes:
      - db_data:/var/lib/mysql
      - ./db-mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./back-fastapi
      target: production
    container_name: korus-backend
    restart: unless-stopped
    env_file:
      - ./.env.prod
    working_dir: /code
    depends_on:
      - db

  frontend:
    build:
      context: ./front-next
      target: production
    container_name: korus-frontend
    restart: unless-stopped
    env_file:
      - ./.env.front.prod
    working_dir: /usr/src/app
    depends_on:
      - backend

  nginx:
    build:
      context: ./server-nginx
    container_name: korus-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./server-nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - uploads_data:/var/www/uploads:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
  uploads_data:
